### ISSUE TITLE
blend files

### ISSUE THREAD

**Issue by carlosedubarreto** [lanthaon/sl-animation-blender#1]
Hello, thanks for your work....
I was trying to test your codes using the blend file, but I saw that the blend file in reality is a text file with this inside

```
version https://git-lfs.github.com/spec/v1
oid sha256:fb71b6b8603639883e2d5dfcdd91acc9a0d4b78430a0021816c6872a32ccc2b7
size 164852

```

I think that could be a problem when you were uploading it.

**Comment by lanthaon** [comment]
Hi Carlos,
thank you for reporting this problem. It happens when you just download the project as a ZIP file, there are two ways to solve this problem:

1. download each large file over 100MB manually from the GitHub page, e.g. https://github.com/lanthaon/sl-animation-blender/blob/main/blender_scripts/animate_avatar.blend
2. clone the project with Git LFS installed https://git-lfs.github.com/

When you choose option 1, move the files to their original folder first, if not some relative file paths will break.

**Comment by carlosedubarreto** [comment]
Thanks a lot @lanthaon .

I didnt know that.

And btw, thank also for the inspiration. Using the mp_landmark/main.py as a reference, I could make my own mediapipe for blender.

Thank you a lot....
